parameters:
  LibraryName: ''

steps:
- task: Npm@1
  displayName: 'Git Clean'
  inputs:
    command: custom

    verbose: false

    customCommand: 'run ci-git-clean'

- task: Npm@1
  displayName: 'Git Config'
  inputs:
    command: custom

    verbose: false

    customCommand: 'run ci-git-config'