parameters:
  LibraryName: ''

steps:
- task: Npm@1
  displayName: 'Git Clean'
  inputs:
    command: custom

    verbose: false

    customCommand: 'git reset --hard'

- task: Npm@1
  displayName: 'Git Config'
  inputs:
    command: custom

    verbose: false

    customCommand: 'git config --global user.email \"matthiasm@live.de\" && git config --global user.name \"Matthias Mueller\"'