steps:
- powershell: |
   $filePath= Join-Path -Path $(Build.Repository.LocalPath) -ChildPath "\src\environments\environment.prod.ts"
         
   $environmentContent = Get-Content $filePath
   $replaced = $environmentContent -replace '__BuildVersion__', '$(Build.BuildNumber)'
      
   Set-Content -Path $filePath -value $replaced
   
  displayName: 'Update Prod-Environment BuildVersion'
