parameters:
  FolderToPack: ''
  BuildConfiguration: ''

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: 'Default'
  steps:
  - template: ../Steps/Initialize_And_Test.yaml
    parameters:
      BuildConfiguration: ${{ parameters.BuildConfiguration }}
  - template: ../Steps/Pack_And_Publish_To_NuGet.yaml
    parameters:
      FolderToPack: ${{ parameters.FolderToPack }}