parameters:
  dependsOnJobName: ''

jobs:
- job: CreateAzureDevOpsRelease
  pool: server
  displayName: 'Create Azure DevOps Release'
  dependsOn: ${{ parameters.dependsOnJobName }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - task: AzureFunction@1
    displayName: 'Create Release'
    inputs:
      function: 'https://tfsreleasemanagementsystem.azurewebsites.net/api/CreateRelease'

      key: '$(TfsReleaseManagementKey)'

      body: |  
       {
           "workItemTypeName": "Release",
           "fields": [
               {
                  "name": "custom.version",
                  "value": "$(Build.BuildNumber)"
               },
               {
                  "name": "Title",
                  "value": "Build $(Build.BuildNumber)"
               }
           ],
           "relations": [
               {
                   "RelationTypeDescription": "System.LinkTypes.Hierarchy-Reverse",
                   "TargetWorkItemId": $(ParentWorkItemId)
               }
           ]
       }
