parameters:
  DependsOnJobName: ''
  ParentWorkItemId: ''

jobs:
- job: CreateAzureDevOpsRelease
  pool: server
  displayName: 'Create Azure DevOps Release'
  dependsOn: ${{ parameters.DependsOnJobName }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  steps:
  - task: AzureFunction@1
    displayName: 'Create Release Work Item'
    inputs:
      function: 'https://tfsreleasemanagementsystem.azurewebsites.net/api/CreateRelease'

      key: 'KCw8zHoDdJ2lGj2VzaHCaywIVZTGyT8MldAkAlcdFb63V9ephxuA1A=='

      headers: |  
       {
       "Content-Type":"application/json"
       }

      body: |  
       {
           "buildId": $(Build.BuildId),
           "buildVersion": "$(Build.BuildNumber)",
           "parentWorkItemId": "${{ParentWorkItemId}}"
       }