parameters:

jobs:
- job: CreateAzureDevOpsRelease
  displayName: 'Create Azure DevOps Release'
  steps:
  - template: AzureDevOps/Templates/StepTemplates/Angular/Initialize_And_Test.yaml@ALMStuff
