steps:
- powershell: |
   $filePath= Join-Path -Path $(Build.Repository.LocalPath) -ChildPath "\src\environments\environment.prod.ts"
         
   Write-Host "Repository LocalPath: $(Build.Repository.LocalPath)"
   Write-Host "Environment-File: $filePath"
   Write-Host "Build Number: $(Build.BuildNumber)"

   $environmentContent = Get-Content $filePath -Verbose
   $replaced = $environmentContent -replace '__BuildVersion__', '$(Build.BuildNumber)'
      
   Set-Content -Path $filePath -value $replaced -Verbose
   
  displayName: 'Update Prod-Environment Version'
