jobs:
- job: 'BuildAndPublishAzureDevOpsExtension'
  displayName: 'Build and publish Azure DevOps Extension'
  pool:
    name: 'Default'
  steps:
  - template: ../Steps/Git_Config.yaml
  - template: ../Steps/Initialize_And_Test.yaml
    parameters:
      ExecuteIntegrationTests: false
  - template: ../Steps/Build_Production.yaml
  - template: ../Steps/Update_NPM_Package_Version.yaml
    parameters:
      WorkingDir: dist
  - template: ../Steps/Update_Tfx_Version.yaml
  - template: ../Steps/Publish_Tfx_Package.yaml