jobs:
- job: 'BuildAndPublishAzureDevOpsExtension'
  displayName: 'Build and publish Azure DevOps Extension'
  pool:
    name: 'Default'
  steps:
  - template: ../Steps/Angular/Configure_Git.yaml
  - template: ../Steps/Angular/Initialize_And_Test.yaml
    parameters:
      ExecuteIntegrationTests: false
  - template: ../Steps/Angular/Build_Production.yaml
  - template: ../Steps/Update_Version.yaml
    parameters:
      WorkingDir: dist
  - template: ../Steps/Angular/Update_Tfx_Version.yaml
  - template: ../Steps/Angular/Publish_Tfx_Package.yaml